version: "3.9"
services:
  users-db:
    image: postgres:16-alpine
    container_name: keycloak_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5444:5432"
    restart: always