spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5444/users_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
service:
  phone:
    url: http://localhost:8282